title: Shiman Zhang's Homepage
page-top-title: Shiman Zhang
top-section-bg-text: Computer Science
home-subtitle: Shiman Zhang&ensp;|&ensp;张诗曼
copyright-text: '&copy; Shiman Zhang 2024-2025. All Rights Reserved.'
